import React,{useMemo,useState}from'react';
import{BarChart3,WalletCards,Package,ArrowUpRight,ChevronRight,TriangleAlert}from'lucide-react';
import{ResponsiveContainer,ComposedChart,Bar,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend}from'recharts';
import{money,buildDRE,buildExecutiveInsights,filterByPeriod,monthKey}from'../utils/erpEngine';
const POS='#16a34a',NEG='#dc2626',INK='#111111';
function KPI({icon:Icon,title,value,sub,onClick,tone='neutral'}){return <button className={`kpi-card dashboard-kpi ${tone}`} onClick={onClick}><div className="kpi-head"><span className="icon-chip"><Icon size={18}/></span><span>{title}</span></div><strong>{value}</strong><small>{sub}</small><ArrowUpRight className="card-arrow" size={15}/></button>}
const monthLabel=k=>{if(!/^\d{4}-\d{2}$/.test(k))return k;const[y,m]=k.split('-');return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(Number(y),Number(m)-1,1))};
export default function Dashboard({data,setPage}){
 const{products=[],finance=[],sales=[],purchases=[],invoices=[]}=data;const[period,setPeriod]=useState('all');
 const periods=useMemo(()=>Array.from(new Set([...sales.map(x=>monthKey(x.date)),...finance.map(x=>monthKey(x.due))].filter(k=>/^\d{4}-\d{2}$/.test(k)))).sort().reverse(),[sales,finance]);
 const ps=useMemo(()=>filterByPeriod(sales.filter(s=>!['Cancelada','Cancelado'].includes(s.status)),'date',period),[sales,period]);const pf=useMemo(()=>filterByPeriod(finance,'due',period),[finance,period]);const dre=useMemo(()=>buildDRE({sales:ps,finance:pf}),[ps,pf]);
 const stockValue=useMemo(()=>products.reduce((s,p)=>s+(Number(p.cost)||0)*(Number(p.stock)||0),0),[products]);
 const chart=useMemo(()=>{const m={};sales.filter(s=>!['Cancelada','Cancelado'].includes(s.status)).forEach(s=>{const k=monthKey(s.date);m[k]??={key:k,m:monthLabel(k),receitas:0,saidas:0,resultado:0};const revenue=Number(s.total)||0,cmv=(s.items||[]).reduce((a,i)=>a+(Number(i.cost)||0)*(Number(i.qty)||1),0);m[k].receitas+=revenue;m[k].saidas+=cmv});finance.filter(x=>x.type==='pay'&&x.status!=='cancelled').forEach(x=>{const k=monthKey(x.due);m[k]??={key:k,m:monthLabel(k),receitas:0,saidas:0,resultado:0};m[k].saidas+=Number(x.amount)||0});return Object.values(m).sort((a,b)=>a.key.localeCompare(b.key)).slice(-6).map(x=>({...x,resultado:x.receitas-x.saidas}))},[sales,finance]);
 const insights=useMemo(()=>buildExecutiveInsights({products,finance,sales,purchases,invoices}).slice(0,3),[products,finance,sales,purchases,invoices]);const fallback=[{m:'Atual',receitas:dre.gross,saidas:Math.max(0,dre.gross-dre.net),resultado:dre.net}];
 return <section className="page"><div className="title-row dashboard-title"><div><h1>Dashboard</h1><p>Visão limpa para acompanhar o que realmente exige decisão.</p></div><div className="dashboard-title-actions"><select className="period-input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Todos os períodos</option>{periods.map(k=><option key={k} value={k}>{monthLabel(k)}</option>)}</select></div></div><div className="kpi-grid dashboard-kpis three"><KPI tone="positive" icon={BarChart3} title="Faturamento" value={money(dre.gross)} sub="receita do período" onClick={()=>setPage('sales')}/><KPI tone={dre.net>=0?'positive':'negative'} icon={WalletCards} title="Resultado" value={money(dre.net)} sub="DRE gerencial" onClick={()=>setPage('finance')}/><KPI icon={Package} title="Estoque" value={money(stockValue)} sub={`${products.reduce((s,p)=>s+(Number(p.stock)||0),0)} unidades`} onClick={()=>setPage('stock')}/></div><div className="dashboard-simple-grid advanced"><div className="panel dashboard-chart-panel"><div className="panel-head"><div><h3>Receitas x saídas</h3><p>Últimos períodos consolidados, sem vendas canceladas.</p></div><button onClick={()=>setPage('reports')}>Relatórios</button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart.length?chart:fallback} barGap={5} barCategoryGap="34%"><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eeeeee"/><XAxis dataKey="m"/><YAxis/><Tooltip formatter={money}/><Legend/><Bar dataKey="receitas" name="Receitas" fill={POS} radius={[2,2,0,0]} barSize={14}/><Bar dataKey="saidas" name="Saídas" fill={NEG} radius={[2,2,0,0]} barSize={14}/><Line type="monotone" dataKey="resultado" name="Resultado" stroke={INK} strokeWidth={2} dot={{r:3}}/></ComposedChart></ResponsiveContainer></div></div><div className="panel decision-panel"><div className="panel-head"><div><h3>Prioridades</h3><p>Somente os principais alertas do momento.</p></div><TriangleAlert size={18}/></div>{insights.map(x=><button key={x.title} className={`decision-row ${x.tone}`} onClick={()=>setPage(x.page)}><i className={x.tone==='danger'?'negative-dot':'positive-dot'}/><span><b>{x.title}</b><small>{x.detail}</small></span><strong>{x.value}</strong><ChevronRight size={16}/></button>)}</div></div></section>
}
