import React,{useMemo,useState}from'react';
import{Search,CheckCircle2,ExternalLink,RefreshCw,AlertTriangle,Send,ArrowUpRight,PackagePlus,Command,ClipboardCheck}from'lucide-react';
import{smartProduct}from'../utils/productAI';import{searchOfficialNCM,officialNcmUrl}from'../services/ncmService';import PageHeader from'../components/PageHeader';import{toast}from'../components/ToastHost';import{addAudit}from'../utils/audit';import{uid}from'../utils/ids';import{can,currentRole}from'../utils/permissions';
import{interpretCommand,money}from'../utils/erpEngine';
export default function Intelligence({products,setProducts,setPage,data}){
 const[mode,setMode]=useState('command');const[command,setCommand]=useState('Quais produtos estão com margem abaixo de 35%?');const[answer,setAnswer]=useState(()=>interpretCommand('Quais produtos estão com margem abaixo de 35%?',data||{products}));
 const[text,setText]=useState('');const[draft,setDraft]=useState(()=>smartProduct(text,products));const[results,setResults]=useState([]);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');
 const history=useMemo(()=>{try{return JSON.parse(localStorage.getItem('home-ai-history')||'[]')}catch{return[]}},[]);
 const ask=()=>{const a=interpretCommand(command,{...(data||{}),products});setAnswer(a);addAudit('Consulta executiva','Assistente',command)};
 const interpret=()=>{setDraft(smartProduct(text,products));setResults([]);setErr('')};
 const lookup=async()=>{setLoading(true);setErr('');try{const r=await searchOfficialNCM(`${draft.category} ${draft.name}`,10);setResults(r);if(!r.length)setErr('Nenhuma correspondência forte encontrada. Refine a descrição ou abra a consulta oficial.')}catch(e){setErr(e.message||'Falha na consulta oficial.')}finally{setLoading(false)}};
 const choose=n=>setDraft(d=>({...d,ncm:n.code,ncmDescription:n.description,ncmVerified:true}));
 const save=()=>{if(!can('products.write'))return toast(`O perfil ${currentRole()} não pode criar produtos.`,'warning','Permissão');setProducts(p=>[{...draft,id:uid('prd'),reserved:0,createdAt:new Date().toISOString()},...p]);addAudit('Produto criado pelo assistente','Produtos',`${draft.name} · ${draft.sku}`);const h=[{at:new Date().toISOString(),text,name:draft.name,sku:draft.sku,ncm:draft.ncm},...history].slice(0,20);localStorage.setItem('home-ai-history',JSON.stringify(h));toast(draft.ncmVerified?'Produto cadastrado com classificação fiscal confirmada.':'Produto cadastrado com NCM pendente para revisão.','success','Produtos');setPage('products')};
 return <section className="page"><PageHeader title="Assistente de Gestão" subtitle="Consultas operacionais e cadastro guiado usando os dados do próprio ERP." action={<div className="segmented"><button className={mode==='command'?'active':''} onClick={()=>setMode('command')}><Command size={15}/>Consultas</button><button className={mode==='product'?'active':''} onClick={()=>setMode('product')}><PackagePlus size={15}/>Cadastrar produto</button></div>}/>
 {mode==='command'?<div className="intelligence-command-grid"><div className="panel intelligence-console"><div className="section-kicker"><Command size={17}/> CENTRAL DE COMANDO</div><h2>Pergunte sobre a operação.</h2><p className="muted">O sistema cruza os dados já registrados e responde sem alterar nada sem sua confirmação.</p><div className="command-composer"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Ex.: títulos vencidos, projeção de caixa, estoque baixo..."/><button onClick={ask}><Send size={17}/>Analisar</button></div><div className="command-suggestions">{['Estoque baixo','Títulos vencidos','Projeção de caixa','DRE','Produtos com margem abaixo de 35%','Se as vendas caírem 15%'].map(x=><button key={x} onClick={()=>{setCommand(x);setAnswer(interpretCommand(x,{...(data||{}),products}))}}>{x}</button>)}</div>{answer&&<div className="ai-answer"><div className="ai-answer-head"><div><span>RESPOSTA DO SISTEMA</span><h3>{answer.title}</h3><p>{answer.summary}</p></div>{answer.action&&<button onClick={()=>setPage(answer.action.page)}>{answer.action.label}<ArrowUpRight size={15}/></button>}</div>{answer.kind==='cards'&&<div className="ai-answer-cards">{answer.cards.map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div>}{answer.kind==='table'&&<div className="ai-table"><table><thead><tr>{Object.keys(answer.rows[0]||{}).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{answer.rows.slice(0,12).map((r,i)=><tr key={i}>{Object.values(r).map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!answer.rows.length&&<p className="empty">Nenhum registro atende aos critérios.</p>}</div>}</div>}</div><aside className="panel intelligence-side"><div className="section-kicker">ATALHOS</div><h3>Consultas úteis</h3>{['Margem por produto','Contas vencidas','Risco de ruptura','Resultado gerencial','Exposição de caixa','Situação fiscal'].map(x=><div className="feature-line" key={x}><CheckCircle2 size={15}/><span>{x}</span></div>)}<hr/><h3>Importante</h3><p>As consultas usam apenas os dados atuais do ERP. Classificação fiscal continua dependendo de fonte oficial e validação humana.</p></aside></div>:
 <div className="intelligence-grid"><div className="panel intelligence-main"><div className="section-kicker"><ClipboardCheck size={17}/> CADASTRO ASSISTIDO</div><h2>Descreva o produto do seu jeito.</h2><p className="muted">Categoria, SKU, materiais prováveis, fornecedor, margem e preço são preparados automaticamente. O NCM é pesquisado na tabela oficial armazenada no próprio ERP.</p><div className="smart-composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Ex.: Poltrona Luna em linho bege, fornecedor Nome do fornecedor, custo 1320"/><button onClick={interpret}><ClipboardCheck size={17}/>Preparar cadastro</button></div><div className="field-grid large">{[['Nome',draft.name],['Categoria',draft.category],['SKU',draft.sku],['Fornecedor',draft.supplier],['Material',draft.material||'—'],['Unidade',draft.unit],['Custo',money(draft.cost)],['Preço sugerido',money(draft.price)],['Margem',`${draft.margin.toFixed(1)}%`],['Estoque mínimo',draft.minStock]].map(([a,b])=><div className="field-card editable" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="ncm-box"><div><div className="section-kicker"><Search size={15}/> CLASSIFICAÇÃO FISCAL</div><h3>NCM pela tabela local oficial</h3><p>Nenhum código é gerado aleatoriamente. A busca usa a tabela NCM vigente de 27/09/2026 armazenada no ERP e você confirma a correspondência.</p></div><div className="ncm-actions"><button className="secondary" onClick={lookup} disabled={loading}>{loading?<RefreshCw className="spin" size={16}/>:<Search size={16}/>} {loading?'Consultando...':'Buscar NCM local'}</button><a className="link-btn" href={officialNcmUrl()} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Abrir Classif</a></div></div>{draft.ncmVerified&&<div className="selected-ncm"><CheckCircle2 size={18}/><div><b>{draft.ncm}</b><span>{draft.ncmDescription}</span></div></div>}{err&&<div className="warning-box"><AlertTriangle size={17}/>{err}</div>}{results.length>0&&<div className="ncm-results">{results.map(r=><button key={r.code} onClick={()=>choose(r)}><b>{r.code}</b><span>{r.description}</span><em>Selecionar</em></button>)}</div>}<div className="confirm-bar"><div><b>Revisão obrigatória antes de salvar</b><span>NCM e tributação devem ser conferidos conforme a mercadoria real.</span></div><button className="primary" onClick={save}>Confirmar cadastro</button></div></div><aside className="panel intelligence-side"><div className="section-kicker">AUTOMAÇÕES</div><h3>O cadastro já faz</h3>{['Cria categoria automaticamente','Gera SKU sem duplicidade','Extrai fornecedor e custo','Calcula preço e margem','Sugere estoque mínimo','Consulta NCM oficial sem depender da internet','Mantém NCM vazio sem confirmação'].map(x=><div className="feature-line" key={x}><CheckCircle2 size={15}/><span>{x}</span></div>)}</aside></div>}</section>
}
