import React,{useMemo,useState}from'react';
import{ClipboardCheck,Search,Truck,PackageCheck,Clock3,CheckCircle2,Eye,ArrowRight,MapPin,UserRound}from'lucide-react';
import PageHeader from'../components/PageHeader';import Modal from'../components/Modal';import{safeReadArray,safeWrite}from'../utils/storage';import{toast}from'../components/ToastHost';import{addAudit}from'../utils/audit';import{money}from'../utils/erpEngine';

const ORDER_KEY='home-orders-v217';
const STAGES=['Aguardando separação','Em separação','Pronto','Em rota','Concluído','Cancelado'];
const nextStage=s=>({
 'Aguardando separação':'Em separação','Em separação':'Pronto','Pronto':'Em rota','Em rota':'Concluído'
}[s]||s);
export default function Orders({sales=[]}){
 const[orders,setOrders]=useState(()=>safeReadArray(ORDER_KEY,[]));
 const[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[detail,setDetail]=useState(null);
 const deliveries=safeReadArray('home-deliveries-v29',[]);
 const list=useMemo(()=>orders.filter(o=>`${o.client||''} ${o.saleId||''} ${o.seller||''} ${(o.items||[]).map(i=>i.name).join(' ')}`.toLowerCase().includes(q.toLowerCase())).filter(o=>filter==='all'||o.status===filter),[orders,q,filter]);
 const stats=useMemo(()=>({open:orders.filter(o=>!['Concluído','Cancelado'].includes(o.status)).length,separating:orders.filter(o=>o.status==='Em separação').length,ready:orders.filter(o=>o.status==='Pronto').length,delivery:orders.filter(o=>o.fulfillment==='Entrega'&&!['Concluído','Cancelado'].includes(o.status)).length}),[orders]);
 const persist=next=>{setOrders(next);safeWrite(ORDER_KEY,next)};
 const advance=o=>{const status=nextStage(o.status);if(status===o.status)return;const now=new Date().toISOString();const next=orders.map(x=>x.id===o.id?{...x,status,updatedAt:now}:x);persist(next);const ds=safeReadArray('home-deliveries-v29',[]);if(o.fulfillment==='Entrega'){const map={'Em separação':'Em separação','Pronto':'Agendada','Em rota':'Em rota','Concluído':'Entregue'};if(map[status])safeWrite('home-deliveries-v29',ds.map(d=>String(d.saleId)===String(o.saleId)?{...d,status:map[status]}:d))}addAudit('Etapa do pedido alterada','Pedidos',`Venda #${o.saleId} · ${o.status} → ${status}`);toast(`Pedido movido para ${status}.`,'success','Pedidos')};
 const saleFor=o=>sales.find(s=>String(s.id)===String(o.saleId));
 return <section className="page"><PageHeader title="Pedidos" subtitle="Acompanhe a operação depois da venda: separação, retirada, entrega e conclusão."/>
  <div className="order-kpis"><div><small>Em aberto</small><b>{stats.open}</b></div><div><small>Em separação</small><b>{stats.separating}</b></div><div><small>Prontos</small><b>{stats.ready}</b></div><div><small>Com entrega</small><b>{stats.delivery}</b></div></div>
  <div className="orders-intro"><ClipboardCheck size={18}/><div><b>Venda acontece somente no Caixa.</b><p>Depois da finalização, o pedido aparece aqui automaticamente para a equipe acompanhar separação, retirada ou entrega.</p></div></div>
  <div className="orders-toolbar"><div className="orders-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, venda, vendedora ou produto..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></div>
  <div className="orders-list"><div className="orders-row orders-head"><span>Pedido</span><span>Cliente</span><span>Atendimento</span><span>Itens</span><span>Total</span><span>Status</span><span>Ações</span></div>{list.map(o=>{const sale=saleFor(o);return <div className="orders-row" key={o.id}><span><b>#{o.saleId}</b><small>{o.date||'—'}</small></span><span><b>{o.client||'Consumidor final'}</b><small>{o.seller||'Sem vendedora'}</small></span><span><b>{o.fulfillment||'Retirada'}</b><small>{o.fulfillment==='Entrega'?'Entrega programada':'Retirada na loja'}</small></span><span><b>{(o.items||[]).reduce((a,i)=>a+(Number(i.qty)||0),0)} un.</b><small>{(o.items||[]).length} produto(s)</small></span><span><b>{money(Number(o.total)||Number(sale?.total)||0)}</b><small>{sale?.payment||'—'}</small></span><span><em className={`order-status ${o.status==='Concluído'?'done':o.status==='Cancelado'?'cancelled':''}`}>{o.status}</em></span><span className="order-actions"><button className="secondary" onClick={()=>setDetail(o)} title="Detalhes"><Eye size={14}/></button>{!['Concluído','Cancelado'].includes(o.status)&&<button className="primary compact" onClick={()=>advance(o)}><ArrowRight size={14}/>{nextStage(o.status)}</button>}</span></div>})}{!list.length&&<p className="empty-list">Nenhum pedido encontrado.</p>}</div>
  {detail&&<Modal title={`Pedido da venda #${detail.saleId}`} onClose={()=>setDetail(null)} wide><div className="order-detail"><div className="order-detail-grid"><div><small>Cliente</small><b>{detail.client}</b></div><div><small>Vendedora</small><b>{detail.seller||'—'}</b></div><div><small>Operador</small><b>{detail.operator||'—'}</b></div><div><small>Atendimento</small><b>{detail.fulfillment}</b></div><div><small>Status</small><b>{detail.status}</b></div><div><small>Total</small><b>{money(detail.total||0)}</b></div></div><div className="order-items">{(detail.items||[]).map((i,idx)=><div key={`${i.productId}-${idx}`}><PackageCheck size={15}/><span><b>{i.name}</b><small>{i.qty} × {money(i.price||0)}</small></span></div>)}</div>{detail.fulfillment==='Entrega'&&(()=>{const d=deliveries.find(x=>String(x.saleId)===String(detail.saleId));return d?<div className="order-delivery-box"><MapPin size={15}/><div><b>{d.address||'Endereço não informado'}</b><small>{d.date||'Sem data'} · {d.window||'Sem janela'} · {d.status}</small></div></div>:<div className="order-delivery-box"><Truck size={15}/><div><b>Entrega ainda sem programação</b><small>Abra Pós-venda para completar os dados da entrega.</small></div></div>})()}</div></Modal>}
 </section>
}
