import React, { useEffect, useMemo, useState } from 'react';
import {
  Plus,
  Search,
  ClipboardPlus,
  Trash2,
  Pencil,
  ExternalLink,
  Package,
  ChevronRight,
  CheckCircle2,
  AlertTriangle,
  History,
  Tag,
  ChartNoAxesColumnIncreasing,
  Image as ImageIcon,
  Upload,
  WandSparkles,
  ShieldCheck,
  Boxes,
  DollarSign,
  Ruler,
  FileText,
  Barcode,
} from 'lucide-react';
import { smartProduct } from '../utils/productAI';
import { searchOfficialNCM, officialNcmUrl } from '../services/ncmService';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import ConfirmDialog from '../components/ConfirmDialog';
import { toast } from '../components/ToastHost';
import { addAudit } from '../utils/audit';
import { money, getProductMargin, pct, suggestReorder } from '../utils/erpEngine';
import { uid } from '../utils/ids';
import { putAttachment, getAttachment } from '../utils/attachments';
import { can, currentRole } from '../utils/permissions';

const fileToDataUrl = (file) =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });

const ProductImageSlot = ({ image, imageAttachmentId, compact = false, onUpload }) => {
  const [src,setSrc]=useState(image||'');
  useEffect(()=>{let alive=true;if(image){setSrc(image);return()=>{alive=false}}if(imageAttachmentId){getAttachment(imageAttachmentId).then(x=>{if(alive)setSrc(x?.dataUrl||'')}).catch(()=>{})}else setSrc('');return()=>{alive=false}},[image,imageAttachmentId]);
  return <div className={`product-image-slot ${compact ? 'compact' : ''}`}>
    {src ? <img src={src} alt="Produto" /> : <div className="product-image-empty"><ImageIcon size={compact ? 16 : 22} /><span>{compact ? 'Imagem' : 'Espaço para imagem'}</span></div>}
    {onUpload && <label className="image-upload-action"><Upload size={14} /><span>{src ? 'Trocar imagem' : 'Selecionar imagem'}</span><input type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const dataUrl=await fileToDataUrl(file);const id=uid('att');await putAttachment({id,name:file.name||'produto',type:file.type||'image/*',dataUrl,module:'Produtos',recordId:''});setSrc(String(dataUrl));onUpload({image:'',imageAttachmentId:id})}catch{toast('Não foi possível carregar a imagem do produto.','warning','Imagem')}finally{e.target.value=''}}}/></label>}
  </div>;
};

const createBlankProduct = () => ({
  name: '', category: '', subcategory: '', sku: '', reference: '', ean: '',
  brand: '', collection: '', supplier: '', unit: 'UN', image: '', imageAttachmentId:'',
  cost: 0, price: 0, promotionalPrice: 0, stock: 0, reserved: 0, minStock: 1, location: '',
  material: '', finish: '', color: '', width: '', height: '', depth: '', weight: '',
  warrantyMonths: 0, warrantyType: '', warrantyStart: '', warrantyNotes: '',
  ncm: '', ncmDescription: '', ncmVerified: false, cest: '', cfop: '', origin: '0', taxStatus: '',
  description: '', notes: '', tags: [], active: true, autoGenerated: false,
});

export default function Products({ products, setProducts, setPage, sales = [] }) {
  const canSeeCost = can('products.cost.view');
  const canWriteProduct = can('products.write');
  const [q, setQ] = useState('');
  const [modal, setModal] = useState(false);
  const [detail, setDetail] = useState(null);
  const [edit, setEdit] = useState(null);
  const [draft, setDraft] = useState(null);
  const [ncmList, setNcmList] = useState([]);
  const [ncmQuery, setNcmQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [filter, setFilter] = useState('active');
  const [archiveId, setArchiveId] = useState(null);
  const [productPage, setProductPage] = useState(1);
  const pageSize = 100;
  const list = useMemo(
    () =>
      products.filter((p) => {
        const hit = (p.name + p.sku + p.category + p.supplier).toLowerCase().includes(q.toLowerCase());
        const state = filter === 'all' ? true : filter === 'archived' ? p.active === false : p.active !== false;
        return hit && state;
      }),
    [products, q, filter]
  );
  const totalPages = Math.max(1, Math.ceil(list.length / pageSize));
  const pagedList = useMemo(() => list.slice((productPage - 1) * pageSize, productPage * pageSize), [list, productPage]);
  useEffect(() => { setProductPage(1); }, [q, filter]);
  useEffect(() => { if (productPage > totalPages) setProductPage(totalPages); }, [productPage, totalPages]);

  const startNew = () => { setDraft(createBlankProduct()); setNcmList([]); setNcmQuery(''); setModal(true); };

  const gen = async () => {
    if (!draft?.name?.trim()) return toast('Descreva o produto para gerar o cadastro.', 'warning', 'Cadastro de produto');
    const auto = smartProduct(draft.name, products);
    const prepared = {
      ...draft,
      ...auto,
      id: draft.id,
      image: draft.image || auto.image || '',
      imageAttachmentId: draft.imageAttachmentId || auto.imageAttachmentId || '',
      cost: Number(draft.cost || auto.cost || 0),
      price: Number(draft.price || auto.price || 0),
      stock: Number(draft.stock || 0),
      supplier: draft.supplier || auto.supplier || '',
      ncm: '', ncmDescription: '', ncmVerified: false, ncmSource: '',
      autoGenerated: true,
    };
    setDraft(prepared);
    setNcmList([]);
    const generatedNcmQuery = [prepared.category, prepared.name, prepared.material, prepared.finish].filter(Boolean).join(' ');
    setNcmQuery(generatedNcmQuery);
    setBusy(true);
    try {
      const results = await searchOfficialNCM(generatedNcmQuery, 8);
      setNcmList(results);
      if (results[0]) {
        setDraft((current) => ({
          ...current,
          ncm: results[0].code,
          ncmDescription: results[0].description,
          ncmVerified: false,
          ncmSource: 'Tabela NCM local 27/09/2026',
        }));
        toast('Cadastro gerado e NCM pesquisado na tabela oficial armazenada no próprio ERP. Confirme a sugestão antes de salvar.', 'success', 'Produto preparado');
      }
    } catch (e) {
      // A consulta externa pode estar indisponível no modo local. O cadastro segue normalmente com NCM pendente.
      setNcmList([]);
    } finally {
      setBusy(false);
    }
  };

  const searchNcm = async () => {
    if (!draft) return;
    const query = String(ncmQuery || [draft.category, draft.name, draft.material, draft.finish].filter(Boolean).join(' ')).trim();
    if (!query) return toast('Digite o nome, material ou código NCM para pesquisar.', 'warning', 'NCM');
    setBusy(true);
    try {
      const results = await searchOfficialNCM(query, 12);
      setNcmList(results);
      if (!results.length) toast('Nenhum NCM encontrado para essa pesquisa na tabela local.', 'warning', 'NCM');
    } catch (e) {
      console.error('NCM local:', e);
      setNcmList([]);
      toast('A tabela NCM embutida não pôde ser lida. Recarregue o aplicativo.', 'warning', 'NCM');
    } finally {
      setBusy(false);
    }
  };

  const add = () => {
    if (!draft) return;
    if (!can('products.write'))
      return toast(`O perfil ${currentRole()} não pode criar produtos.`, 'warning', 'Permissão');
    if (!draft.name?.trim()) return toast('Informe o nome do produto.', 'warning', 'Cadastro');
    if (!draft.sku?.trim()) return toast('Gere ou informe o SKU antes de salvar.', 'warning', 'Cadastro');
    if (!(Number(draft.price) > 0)) return toast('Informe o preço de venda.', 'warning', 'Cadastro');

    const item = {
      ...draft,
      id: uid('prd'),
      reserved: 0,
      createdAt: new Date().toISOString(),
    };
    setProducts((p) => [item, ...p]);
    addAudit('Produto criado', 'Produtos', `${draft.name} · ${draft.sku}`);
    setModal(false);
    setDraft(null);
    setNcmList([]);
    toast('Produto cadastrado.', 'success', 'Produtos');
  };

  const remove = (id) => setArchiveId(id);

  const confirmArchive = () => {
    if (!can('products.write')) {
      setArchiveId(null);
      return toast(`O perfil ${currentRole()} não pode arquivar produtos.`, 'warning', 'Permissão');
    }
    const item = products.find((x) => String(x.id) === String(archiveId));
    setProducts((p) =>
      p.map((x) =>
        String(x.id) === String(archiveId) ? { ...x, active: false, archivedAt: new Date().toISOString() } : x
      )
    );
    addAudit('Produto arquivado', 'Produtos', item?.name || String(archiveId));
    setArchiveId(null);
    toast('Produto arquivado sem apagar o histórico.', 'success', 'Produtos');
  };

  const saveEdit = () => {
    if (!edit) return;
    if (!can('products.write'))
      return toast(`O perfil ${currentRole()} não pode editar produtos.`, 'warning', 'Permissão');
    const old = products.find((x) => x.id === edit.id);
    setProducts((p) => p.map((x) => (x.id === edit.id ? { ...x, ...edit, updatedAt: new Date().toISOString() } : x)));
    let hist={};
    try{const raw=JSON.parse(localStorage.getItem('home-product-history')||'{}');hist=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{}}catch{hist={}}
    hist[edit.id] = [
      {
        at: new Date().toISOString(),
        costBefore: old?.cost,
        priceBefore: old?.price,
        costAfter: Number(edit.cost),
        priceAfter: Number(edit.price),
      },
      ...(hist[edit.id] || []),
    ].slice(0, 50);
    localStorage.setItem('home-product-history', JSON.stringify(hist));
    addAudit('Produto editado', 'Produtos', `${edit.name} · custo ${money(edit.cost)} · preço ${money(edit.price)}`);
    setDetail({ ...edit });
    setEdit(null);
  };

  const openDetail = (p) => {
    setDetail(p);
    setEdit(null);
  };

  let history=[];
  if(detail){try{const raw=JSON.parse(localStorage.getItem('home-product-history')||'{}');history=Array.isArray(raw?.[detail.id])?raw[detail.id]:[]}catch{history=[]}}

  return (
    <section className="page">
      <PageHeader
        title="Produtos"
        subtitle="Catálogo, fiscal, custos, preços, margem e histórico no mesmo cadastro."
        action={canWriteProduct ? (
          <button className="primary" onClick={startNew}>
            <Plus size={17} />
            Novo produto
          </button>
        ) : null}
      />

      <div className="toolbar">
        <label className="search">
          <Search size={17} />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar produto, SKU, categoria ou fornecedor..." />
        </label>
        <select className="period-input" value={filter} onChange={(e) => setFilter(e.target.value)}>
          <option value="active">Ativos</option>
          <option value="archived">Arquivados</option>
          <option value="all">Todos</option>
        </select>
        <span>{list.length} registros</span>
      </div>

      <div className="list-panel product-list">
        <div className="list-head product-columns">
          <span>Produto</span>
          <span>Categoria</span>
          <span>SKU / NCM</span>
          <span>Variação</span>
          <span>Preço</span>
          <span>Fornecedor</span>
          <span>Disponível</span>
          <span></span>
        </div>
        {pagedList.map((p) => (
          <div className={`list-row product-columns ${p.active === false ? 'archived' : ''}`} key={p.id} onDoubleClick={() => openDetail(p)}>
            <div className="list-product">
              <ProductImageSlot image={p.image} imageAttachmentId={p.imageAttachmentId} compact />
              <div>
                <b>{p.name}</b>
                <small>{p.supplier}</small>
              </div>
            </div>
            <span>{p.category}</span>
            <span>
              <b className="mono">{p.sku}</b>
              <small>{p.ncm ? `NCM ${p.ncm}` : 'NCM pendente'}</small>
            </span>
            <span><b>{[p.color,p.finish,p.width||p.size].filter(Boolean).join(' · ')||'Padrão'}</b><small>{p.material||'Material não informado'}</small></span>
            <span><b>{money(p.price)}</b></span>
            <span>{p.supplier||'—'}</span>
            <span><b className={(p.stock-(p.reserved||0))<=p.minStock?'danger':''}>{p.stock-(p.reserved||0)} un.</b><small>Físico {p.stock||0} · Reservado {p.reserved||0}</small></span>
            <div className="row-actions">
              <button title="Abrir ficha" onClick={() => openDetail(p)}><ChevronRight size={15}/></button>
              <button title="Ver no estoque" onClick={()=>setPage?.('stock')}><Boxes size={15}/></button>
              {canWriteProduct && <button title="Editar" onClick={() => setEdit({ ...p })}>
                <Pencil size={15} />
              </button>}
              {canWriteProduct && <button title="Arquivar" onClick={() => remove(p.id)}>
                <Trash2 size={15} />
              </button>}
            </div>
          </div>
        ))}
      </div>
      {list.length > pageSize && <div className="product-pagination"><button className="secondary tiny" disabled={productPage===1} onClick={()=>setProductPage(p=>Math.max(1,p-1))}>Anterior</button><span>Página {productPage} de {totalPages} · exibindo {pagedList.length} de {list.length}</span><button className="secondary tiny" disabled={productPage===totalPages} onClick={()=>setProductPage(p=>Math.min(totalPages,p+1))}>Próxima</button></div>}

      {detail && (
        <Modal title="Ficha do produto" onClose={() => setDetail(null)} wide>
          <div className="product-detail-head">
            <div className="product-detail-heading-wrap">
              <ProductImageSlot image={detail.image} imageAttachmentId={detail.imageAttachmentId} />
              <div>
                <span className="section-kicker">{detail.category}</span>
                <h2>{detail.name}</h2>
                <p>
                  {detail.sku} · {detail.supplier}
                </p>
              </div>
            </div>
            {canWriteProduct && <button className="secondary" onClick={() => setEdit({ ...detail })}>
              <Pencil size={15} />
              Editar
            </button>}
          </div>
          <div className="product-detail-grid">
            <div className="detail-stat">
              <Package />
              <span>Estoque</span>
              <b>{detail.stock} un.</b>
              <small>Reservado {detail.reserved || 0} · disponível {detail.stock - (detail.reserved || 0)}</small>
            </div>
            <div className="detail-stat">
              <ChartNoAxesColumnIncreasing />
              <span>Margem</span>
              <b>{canSeeCost?pct(getProductMargin(detail)):'Restrito'}</b>
              <small>
                {canSeeCost ? `Custo ${money(detail.cost)} · preço ${money(detail.price)}` : `Preço ${money(detail.price)}`}
              </small>
            </div>
            <div className="detail-stat">
              <Tag />
              <span>Fiscal</span>
              <b>{detail.ncm || 'Pendente'}</b>
              <small>{detail.ncmVerified ? 'NCM validado' : 'Aguardando validação'}</small>
            </div>
          </div>
          <div className="field-grid">
            {[
              ['Marca', detail.brand || '—'],
              ['Unidade', detail.unit || 'UN'],
              ['Fornecedor', detail.supplier || '—'],
              ['Estoque mínimo', detail.minStock],
              ['Garantia', `${Number(detail.warrantyMonths || 0)} meses · ${detail.warrantyType || 'Não definida'}`],
              ['Localização', detail.location || '—'],
              ...(canSeeCost ? [['Último custo', money(detail.lastPurchaseCost || detail.cost)]] : []),
              ['Reposição sugerida', `${suggestReorder(detail, sales)} un.`],
            ].map(([a, b]) => (
              <div className="field-card" key={a}>
                <span>{a}</span>
                <b>{b}</b>
              </div>
            ))}
          </div>
          <div className="panel embedded">
            <div className="panel-head">
              <div>
                <h3>
                  <History size={16} /> Histórico de custo e preço
                </h3>
                <p>Alterações registradas localmente nesta versão.</p>
              </div>
            </div>
            <div className="compact-list">
              {canSeeCost && history.map((h, i) => (
                <div key={i}>
                  <span>
                    <b>{new Date(h.at).toLocaleString('pt-BR')}</b>
                    <small>
                      Custo {money(h.costBefore)} → {money(h.costAfter)} · Preço {money(h.priceBefore)} → {money(h.priceAfter)}
                    </small>
                  </span>
                </div>
              ))}
              {!history.length && <p className="empty">Nenhuma alteração registrada ainda.</p>}
            </div>
          </div>
        </Modal>
      )}

      {edit && (
        <Modal title="Editar produto" onClose={() => setEdit(null)} wide>
          <div className="product-editor-layout">
            <ProductImageSlot image={edit.image} imageAttachmentId={edit.imageAttachmentId} onUpload={(patch) => setEdit({ ...edit, ...patch })} />
            <div className="form-grid product-form-grid">
              <label className="form-field wide">
                <span>Nome</span>
                <input value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} />
              </label>
              <label className="form-field">
                <span>Categoria</span>
                <input value={edit.category} onChange={(e) => setEdit({ ...edit, category: e.target.value })} />
              </label>
              <label className="form-field">
                <span>SKU</span>
                <input value={edit.sku} onChange={(e) => setEdit({ ...edit, sku: e.target.value })} />
              </label>
              <label className="form-field">
                <span>Fornecedor</span>
                <input value={edit.supplier} onChange={(e) => setEdit({ ...edit, supplier: e.target.value })} />
              </label>
              {canSeeCost && <label className="form-field">
                <span>Custo</span>
                <input type="number" value={edit.cost} onChange={(e) => setEdit({ ...edit, cost: Number(e.target.value) })} />
              </label>}
              <label className="form-field">
                <span>Preço</span>
                <input type="number" value={edit.price} onChange={(e) => setEdit({ ...edit, price: Number(e.target.value) })} />
              </label>
              <label className="form-field">
                <span>Estoque mínimo</span>
                <input type="number" value={edit.minStock} onChange={(e) => setEdit({ ...edit, minStock: Number(e.target.value) })} />
              </label>
              <label className="form-field">
                <span>NCM</span>
                <input value={edit.ncm || ''} onChange={(e) => setEdit({ ...edit, ncm: e.target.value, ncmVerified: false })} />
              </label>
              <label className="form-field"><span>EAN / GTIN</span><input value={edit.ean||''} onChange={(e)=>setEdit({...edit,ean:e.target.value})}/></label>
              <label className="form-field"><span>Referência</span><input value={edit.reference||''} onChange={(e)=>setEdit({...edit,reference:e.target.value})}/></label>
              <label className="form-field"><span>Localização</span><input value={edit.location||''} onChange={(e)=>setEdit({...edit,location:e.target.value})}/></label>
              <label className="form-field"><span>Garantia</span><select value={edit.warrantyMonths??12} onChange={(e)=>setEdit({...edit,warrantyMonths:Number(e.target.value)})}><option value={0}>Sem garantia</option><option value={3}>3 meses</option><option value={6}>6 meses</option><option value={12}>12 meses</option><option value={18}>18 meses</option><option value={24}>24 meses</option><option value={36}>36 meses</option></select></label>
              <label className="form-field"><span>Responsável garantia</span><select value={edit.warrantyType||'Fabricante'} onChange={(e)=>setEdit({...edit,warrantyType:e.target.value})}><option>Fabricante</option><option>Fornecedor</option><option>Loja</option><option>Loja + fabricante</option></select></label>
              <label className="form-field wide"><span>Condições da garantia</span><input value={edit.warrantyNotes||''} onChange={(e)=>setEdit({...edit,warrantyNotes:e.target.value})}/></label>
            </div>
          </div>
          <div className="modal-actions">
            <button className="primary" onClick={saveEdit}>
              Salvar alterações
            </button>
          </div>
        </Modal>
      )}



      {modal && draft && (
        <Modal
          title="Novo produto"
          subtitle="Descreva o produto, gere os dados e revise somente o essencial."
          onClose={() => { setModal(false); setDraft(null); setNcmList([]); setNcmQuery(''); }}
          size="quick-product"
        >
          <div className="quick-product-modal">
            <div className="quick-product-top">
              <ProductImageSlot image={draft.image} imageAttachmentId={draft.imageAttachmentId} compact={false} onUpload={(patch) => setDraft({ ...draft, ...patch })} />
              <div className="quick-product-command">
                <label className="form-field">
                  <span>Descreva o produto *</span>
                  <textarea
                    autoFocus
                    value={draft.name}
                    onChange={(e) => setDraft({ ...draft, name: e.target.value, autoGenerated: false })}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        if (!busy) gen();
                      }
                    }}
                    placeholder="Ex.: Cadeira preta 1,80m, valor 1.290, fornecedor Nome do fornecedor"
                  />
                </label>
                <button className="primary quick-generate" onClick={gen}>
                  <WandSparkles size={16} />Gerar cadastro
                </button>
              </div>
            </div>

            <div className="quick-product-grid">
              {[['Categoria', draft.category || '—'],['SKU', draft.sku || '—'],['Cor', draft.color || '—'],['Medida', draft.sizeLabel || (draft.width ? `${draft.width} cm` : '—')],['Material', draft.material || '—'],['Acabamento', draft.finish || '—'],['Unidade', draft.unit || 'UN']].map(([label,value]) => (
                <div className={`quick-generated-field ${value !== '—' ? 'filled' : ''} ${label === 'Material' && draft.materialInferred ? 'inferred' : ''}`} key={label}>
                  <span>{label === 'Material' && draft.materialInferred ? 'Material provável' : label}</span><b>{value}</b>
                </div>
              ))}
            </div>

            <div className="quick-product-manual">
              <label className="form-field"><span>Preço de venda *</span><input type="number" min="0" step="0.01" value={draft.price || ''} onChange={(e)=>setDraft({...draft,price:Number(e.target.value)})} placeholder="0,00"/></label>
              {canSeeCost && <label className="form-field"><span>Custo</span><input type="number" min="0" step="0.01" value={draft.cost || ''} onChange={(e)=>setDraft({...draft,cost:Number(e.target.value)})} placeholder="0,00"/></label>}
              <label className="form-field"><span>Estoque inicial</span><input type="number" min="0" value={draft.stock || 0} onChange={(e)=>setDraft({...draft,stock:Number(e.target.value)})}/></label>
              <label className="form-field"><span>Fornecedor</span><input value={draft.supplier || ''} onChange={(e)=>setDraft({...draft,supplier:e.target.value})} placeholder="Opcional"/></label>
            </div>
            <div className="quick-ncm-search">
              <label className="form-field">
                <span>Pesquisar NCM na tabela local</span>
                <div className="quick-ncm-search-row">
                  <input
                    value={ncmQuery}
                    onChange={(e)=>setNcmQuery(e.target.value)}
                    onKeyDown={(e)=>{if(e.key==='Enter'){e.preventDefault();if(!busy)searchNcm();}}}
                    placeholder="Ex.: cadeira madeira, sofá estofado ou 9401.69.00"
                  />
                  <button className="secondary" onClick={searchNcm} disabled={busy}>
                    <Search size={15}/>{busy ? 'Pesquisando...' : 'Pesquisar'}
                  </button>
                </div>
                <small>Base oficial embutida no aplicativo · vigente em 27/09/2026 · funciona sem consultar a internet.</small>
              </label>
            </div>

            <div className="quick-ncm-line">
              <div className={draft.ncmVerified ? 'quick-ncm-status verified' : 'quick-ncm-status'}>
                {draft.ncmVerified ? <CheckCircle2 size={16}/> : <AlertTriangle size={16}/>} 
                <span>
                  <b>{draft.ncm ? `NCM ${draft.ncm}${draft.ncmVerified ? ' confirmado' : ' sugerido'}` : 'NCM pendente'}</b>
                  <small>{busy ? 'Consultando a tabela NCM armazenada no próprio ERP...' : (draft.ncmDescription || 'Tabela NCM local vigente em 27/09/2026. A sugestão deve ser confirmada antes de salvar.')}</small>
                </span>
              </div>
              <div className="quick-ncm-actions">
                {draft.ncm && !draft.ncmVerified && <button className="primary" onClick={()=>setDraft(d=>({...d,ncmVerified:true}))}><CheckCircle2 size={15}/>Confirmar NCM</button>}
              </div>
            </div>

            {ncmList.length > 0 && (
              <div className="quick-ncm-results">
                {ncmList.slice(0,4).map((r)=><button key={r.code} onClick={()=>setDraft(d=>({...d,ncm:r.code,ncmDescription:r.description,ncmVerified:false,ncmSource:'Tabela NCM local 27/09/2026'}))}><b>{r.code}</b><span>{r.description}</span></button>)}
              </div>
            )}

            <div className="quick-product-footer">
              <span>{draft.autoGenerated ? 'Dados automáticos preparados' : 'Aguardando geração do cadastro'}</span>
              <div>
                <button className="secondary" onClick={()=>{setModal(false);setDraft(null);setNcmList([]);setNcmQuery('')}}>Cancelar</button>
                <button className="primary" onClick={add}><Package size={16}/>Salvar produto</button>
              </div>
            </div>
          </div>
        </Modal>
      )}

      <ConfirmDialog
        open={!!archiveId}
        title="Arquivar produto"
        message="O produto ficará fora das vendas, mas todo o histórico será preservado."
        confirmLabel="Arquivar produto"
        danger
        onConfirm={confirmArchive}
        onCancel={() => setArchiveId(null)}
      />
    </section>
  );
}
