import React,{useMemo,useState}from'react';
import{BarChart3,Boxes,Users,ShoppingCart,TrendingUp,WalletCards,Download,FileSpreadsheet,Target,UserRound,Truck,CalendarCheck,PackageSearch,Medal,ChartNoAxesCombined}from'lucide-react';
import{ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid,PieChart,Pie,Cell}from'recharts';
import PageHeader from'../components/PageHeader';import{money,buildDRE,getProductMargin,pct,isoToday,dateInBrazil}from'../utils/erpEngine';import{safeReadArray}from'../utils/storage';import{getSalespeople}from'../utils/commercial';
const POS='#16a34a',NEG='#dc2626';const stockPalette=['#14532d','#166534','#15803d','#16a34a','#22c55e','#86efac'];
const csv=(name,rows)=>{const keys=Object.keys(rows[0]||{});const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const txt=[keys.map(esc).join(';'),...rows.map(r=>keys.map(k=>esc(r[k])).join(';'))].join('\n');const blob=new Blob(['\ufeff'+txt],{type:'text/csv;charset=utf-8;'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
export default function Reports({setPage,data}){
 const{products=[],sales=[],finance=[],clients=[],suppliers=[],purchases=[]}=data||{};const[tab,setTab]=useState('overview');const dre=buildDRE({sales,finance});const salesTarget=Number(localStorage.getItem('home-sales-target-monthly')||0);const validSales=sales.filter(s=>!['Cancelada','Cancelado'].includes(s.status));const openTitles=finance.filter(x=>!['paid','cancelled'].includes(x.status));
 const categories=useMemo(()=>{const m={};products.forEach(p=>m[p.category]=(m[p.category]||0)+(Number(p.stock)||0));return Object.entries(m).map(([name,value])=>({name,value}))},[products]);
 const margins=products.map(p=>({name:p.name.slice(0,22),margin:Number(getProductMargin(p).toFixed(1))})).sort((a,b)=>b.margin-a.margin).slice(0,8);
 const sellerCfg=useMemo(()=>getSalespeople(),[]);
 const sellerRows=useMemo(()=>{const m={};for(const s of validSales){const seller=s.seller||'Sem vendedor';m[seller]??={seller,sales:0,total:0,commission:0,realMargin:0};m[seller].sales++;m[seller].total+=Number(s.total)||0;m[seller].commission+=Number(s.commission)||0;m[seller].realMargin+=Number(s.realMargin??0)||0}return Object.values(m).map(x=>{const cfg=sellerCfg.find(s=>s.name===x.seller);const target=Number(cfg?.target)||0;return{...x,target,progress:target?x.total/target*100:0}}).sort((a,b)=>b.total-a.total)},[validSales,sellerCfg]);
 const clientRows=useMemo(()=>{const m={};for(const s of validSales){const name=s.client||'Consumidor final';m[name]??={name,count:0,total:0};m[name].count++;m[name].total+=Number(s.total)||0}return Object.values(m).sort((a,b)=>b.total-a.total).slice(0,15)},[validSales]);
 const supplierRows=useMemo(()=>{const m={};for(const p of purchases){const name=p.supplier||'Não informado';m[name]??={name,count:0,total:0,received:0};m[name].count++;m[name].total+=Number(p.total)||0;if(p.status==='Recebido')m[name].received++}return Object.values(m).sort((a,b)=>b.total-a.total).slice(0,15)},[purchases]);
 const productPerformance=useMemo(()=>{const m=new Map(products.map(p=>[String(p.id),{p,qty:0,revenue:0,lastSale:null}]));for(const s of validSales){for(const i of (s.items||[])){const row=m.get(String(i.productId));if(!row)continue;row.qty+=Number(i.qty)||0;row.revenue+=(Number(i.price)||0)*(Number(i.qty)||0);const at=s.createdAt||s.date;if(at&&(!row.lastSale||new Date(at)>new Date(row.lastSale)))row.lastSale=at}}return[...m.values()]},[products,validSales]);
 const abcRows=useMemo(()=>{const sorted=productPerformance.slice().sort((a,b)=>b.revenue-a.revenue),total=sorted.reduce((s,x)=>s+x.revenue,0);let acc=0;return sorted.map(x=>{acc+=x.revenue;const share=total?acc/total:0;return{...x,abc:share<=.8?'A':share<=.95?'B':'C'}}).filter(x=>x.revenue>0).slice(0,50)},[productPerformance]);
 const deadStock=useMemo(()=>{const now=Date.now(),day=86400000;return productPerformance.map(x=>({...x,days:x.lastSale?Math.floor((now-new Date(x.lastSale).getTime())/day):9999,capital:(Number(x.p.stock)||0)*(Number(x.p.cost)||0)})).filter(x=>(Number(x.p.stock)||0)>0&&x.days>=90).sort((a,b)=>b.days-a.days).slice(0,100)},[productPerformance]);
 const cashLog=safeReadArray('home-cash-log-v23',[]),today=isoToday(),todaySales=validSales.filter(s=>s.date===today),todayLogs=cashLog.filter(x=>(x.at?dateInBrazil(x.at):'')===today);const daily={sales:todaySales.length,total:todaySales.reduce((a,b)=>a+(Number(b.total)||0),0),discounts:todaySales.reduce((a,b)=>a+(Number(b.discount)||0),0),returns:todaySales.reduce((a,b)=>a+(Number(b.returnAmount)||0),0),cashMoves:todayLogs,closed:todayLogs.filter(x=>x.kind==='close')};
 const dailyPayments=useMemo(()=>{const m={};for(const s of todaySales){for(const p of (s.paymentDetails||[{type:s.payment,amount:s.total}]))m[p.type||'Outros']=(m[p.type||'Outros']||0)+(Number(p.amount)||0)}return Object.entries(m).sort((a,b)=>b[1]-a[1])},[todaySales]);
 const cards=[[BarChart3,'Faturamento',money(dre.gross),'sales'],[TrendingUp,'Resultado',money(dre.net),'finance'],[Boxes,'Itens em estoque',products.reduce((s,p)=>s+(Number(p.stock)||0),0),'stock'],[WalletCards,'Títulos em aberto',openTitles.length,'finance'],[Users,'Clientes',clients.length,'clients'],[ShoppingCart,'Compras',purchases.length,'purchases']];
 const exportAll=()=>csv('home-relatorio-produtos.csv',products.map(p=>({Produto:p.name,SKU:p.sku,Categoria:p.category,NCM:p.ncm||'',Estoque:p.stock,Custo:p.cost,Preco:p.price,Margem:pct(getProductMargin(p)),Fornecedor:p.supplier})));
 return <section className="page"><PageHeader title="Relatórios" subtitle="Indicadores gerenciais, desempenho comercial, estoque e fechamento diário." action={<button className="primary" onClick={exportAll}><Download size={16}/>Exportar produtos CSV</button>}/><div className="finance-tabs report-tabs">{[['overview','Visão geral'],['commercial','Comercial'],['stock','Estoque & ABC'],['ranking','Clientes & fornecedores'],['daily','Fechamento diário']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='overview'&&<><div className="report-kpis">{cards.map(([Icon,t,v,p])=><button key={t} onClick={()=>setPage(p)}><Icon/><span><small>{t}</small><b>{v}</b></span><i style={{background:t==='Resultado'?(dre.net>=0?POS:NEG):t==='Títulos em aberto'?NEG:'#111'}}/></button>)}</div><div className="reports-grid"><div className="panel"><div className="panel-head"><div><h3>Margem por produto</h3><p>Top produtos por margem percentual.</p></div></div><div className="report-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={margins} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:11}}/><YAxis type="category" dataKey="name" width={130} tick={{fontSize:10}}/><Tooltip formatter={v=>`${v}%`}/><Bar dataKey="margin" radius={[0,3,3,0]} barSize={14}>{margins.map((x,i)=><Cell key={i} fill={x.margin>=0?POS:NEG}/>)}</Bar></BarChart></ResponsiveContainer></div></div><div className="panel"><div className="panel-head"><div><h3>Estoque por categoria</h3><p>Distribuição das unidades físicas.</p></div></div><div className="report-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories.length?categories:[{name:'Sem dados',value:1}]} dataKey="value" nameKey="name" outerRadius={92}>{(categories.length?categories:[{}]).map((_,i)=><Cell key={i} fill={stockPalette[i%stockPalette.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div></div></>}
 {tab==='commercial'&&<div className="panel table-panel"><div className="panel-head"><div><h3><Target size={17}/> Vendedoras, metas, margem e comissões</h3><p>Meta geral: {salesTarget?money(salesTarget):'não definida'} · cada vendedora pode ter meta e comissão próprias.</p></div></div><table><thead><tr><th>Vendedora</th><th>Vendas</th><th>Faturamento</th><th>Ticket</th><th>Margem real</th><th>Comissão</th><th>Meta</th><th>Progresso</th></tr></thead><tbody>{sellerRows.map((x,idx)=><tr key={x.seller}><td><b>{idx<3&&<Medal size={13}/>} {x.seller}</b></td><td>{x.sales}</td><td>{money(x.total)}</td><td>{money(x.sales?x.total/x.sales:0)}</td><td>{money(x.realMargin)}</td><td>{money(x.commission)}</td><td>{x.target?money(x.target):'—'}</td><td>{x.target?`${Math.min(999,x.progress).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div>}
 {tab==='stock'&&<div className="reports-grid"><div className="panel"><div className="panel-head"><div><h3><ChartNoAxesCombined size={17}/> Curva ABC</h3><p>Classificação por faturamento acumulado dos produtos vendidos.</p></div></div><div className="compact-list">{abcRows.slice(0,30).map(x=><div key={x.p.id}><span><b><em className={`abc-badge abc-${x.abc.toLowerCase()}`}>{x.abc}</em> {x.p.name}</b><small>{x.qty} un. vendidas</small></span><strong>{money(x.revenue)}</strong></div>)}{!abcRows.length&&<p className="empty">Sem vendas suficientes para classificar.</p>}</div></div><div className="panel"><div className="panel-head"><div><h3><PackageSearch size={17}/> Estoque parado</h3><p>Itens com saldo e 90+ dias sem venda.</p></div></div><div className="compact-list">{deadStock.slice(0,30).map(x=><div key={x.p.id}><span><b>{x.p.name}</b><small>{x.days>=9999?'Nunca vendido':`${x.days} dias sem venda`} · {x.p.stock} un.</small></span><strong>{money(x.capital)}</strong></div>)}{!deadStock.length&&<p className="empty">Nenhum estoque parado acima de 90 dias.</p>}</div></div></div>}
 {tab==='ranking'&&<div className="reports-grid"><div className="panel"><div className="panel-head"><div><h3><UserRound size={17}/> Clientes</h3><p>Ranking por faturamento.</p></div></div><div className="compact-list">{clientRows.map(x=><div key={x.name}><span><b>{x.name}</b><small>{x.count} venda(s)</small></span><strong>{money(x.total)}</strong></div>)}</div></div><div className="panel"><div className="panel-head"><div><h3><Truck size={17}/> Fornecedores</h3><p>Volume comprado e entregas recebidas.</p></div></div><div className="compact-list">{supplierRows.map(x=><div key={x.name}><span><b>{x.name}</b><small>{x.received}/{x.count} recebidas</small></span><strong>{money(x.total)}</strong></div>)}</div></div></div>}
 {tab==='daily'&&<div className="panel daily-close-panel"><div className="panel-head"><div><h3><CalendarCheck size={17}/> Fechamento gerencial consolidado de {today}</h3><p>Reúne todas as sessões/terminais do dia em um único resumo.</p></div></div><div className="field-grid"><div className="field-card"><span>Vendas</span><b>{daily.sales}</b></div><div className="field-card"><span>Faturamento</span><b>{money(daily.total)}</b></div><div className="field-card"><span>Descontos</span><b>{money(daily.discounts)}</b></div><div className="field-card"><span>Devoluções</span><b>{money(daily.returns)}</b></div><div className="field-card"><span>Sessões fechadas</span><b>{daily.closed.length}</b></div></div><div className="daily-payment-grid">{dailyPayments.map(([type,value])=><div key={type}><small>{type}</small><b>{money(value)}</b></div>)}</div><div className="compact-list">{daily.cashMoves.slice(0,30).map(x=><div key={x.id}><span><b>{x.kind}</b><small>{x.terminal||'Caixa'} · {x.seller||x.operator||'—'} · {new Date(x.at).toLocaleTimeString('pt-BR')}</small></span><strong>{money(x.amount||0)}</strong></div>)}</div></div>}
 <div className="panel export-panel"><FileSpreadsheet size={20}/><div><h3>Exportações rápidas</h3><p>CSV respeitando os dados atuais do ERP.</p></div><div className="action-row"><button className="secondary" onClick={()=>csv('home-financeiro.csv',finance)}>Financeiro</button><button className="secondary" onClick={()=>csv('home-vendas.csv',sales)}>Vendas</button><button className="secondary" onClick={()=>csv('home-compras.csv',purchases)}>Compras</button><button className="secondary" onClick={()=>csv('home-clientes.csv',clients)}>Clientes</button><button className="secondary" onClick={()=>csv('home-curva-abc.csv',abcRows.map(x=>({Produto:x.p.name,SKU:x.p.sku,Classe:x.abc,Faturamento:x.revenue,Quantidade:x.qty})))}>Curva ABC</button></div></div></section>
}
