import React,{useMemo,useState}from'react';
import{ShoppingCart,WalletCards,RotateCcw,Eye,KeyRound,Search,Store,ReceiptText,Boxes}from'lucide-react';
import PageHeader from'../components/PageHeader';import Modal from'../components/Modal';import ConfirmDialog from'../components/ConfirmDialog';import{toast}from'../components/ToastHost';
import{addAudit}from'../utils/audit';import{money}from'../utils/erpEngine';import{safeRead,commitLocalTransaction,STORAGE_KEYS}from'../utils/storage';import{uid}from'../utils/ids';import{can,currentRole}from'../utils/permissions';import{checkManagerPin}from'../utils/managerPin';import{activeSalespeople}from'../utils/commercial';

export default function Sales({sales,setSales,products,setProducts,clients,setClients,finance,setFinance,setMovements,setInvoices,setPage}){
 const[detailSale,setDetailSale]=useState(null),[pinSale,setPinSale]=useState(null),[pinValue,setPinValue]=useState(''),[confirmCancel,setConfirmCancel]=useState(null),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('todos'),[sellerChange,setSellerChange]=useState(null),[newSeller,setNewSeller]=useState(''),[sellerPin,setSellerPin]=useState('');
 const cashierSales=useMemo(()=>sales.filter(s=>s?.channel==='Caixa'),[sales]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return cashierSales.filter(s=>{const statusOk=statusFilter==='todos'||String(s.status||'').toLowerCase()===statusFilter;const text=[s.id,s.client,s.payment,s.seller,s.sessionCode,(s.items||[]).map(i=>i.name).join(' ')].join(' ').toLowerCase();return statusOk&&(!q||text.includes(q))})},[cashierSales,query,statusFilter]);
 const completed=cashierSales.filter(s=>s.status==='Concluída'),cancelled=cashierSales.filter(s=>s.status==='Cancelada');
 const billed=completed.reduce((a,s)=>a+(Number(s.total)||0),0);
 const cancelSale=sale=>{if(!sale)return;if(!can('sales.cancel'))return toast(`O perfil ${currentRole()} não pode cancelar vendas concluídas.`,'warning','Permissão');setPinSale(sale);setPinValue('')};
 const authorizeCancellation=()=>{if(!checkManagerPin(pinValue))return toast('PIN gerencial inválido.','warning','Autorização');setConfirmCancel(pinSale);setPinSale(null);setPinValue('')};

 const changeSeller=()=>{if(!sellerChange)return;if(!checkManagerPin(sellerPin))return toast('PIN gerencial inválido.','warning','Autorização');if(!newSeller)return toast('Selecione a nova vendedora.','warning','Vendedora');const before=sellerChange.seller||'—',after=newSeller;const next=sales.map(x=>String(x.id)===String(sellerChange.id)?{...x,seller:after,sellerChangedAt:new Date().toISOString(),sellerChangedFrom:before}:x);const tx=commitLocalTransaction(`sale-seller-${sellerChange.id}`,{[STORAGE_KEYS.sales]:next});if(!tx.ok)return toast('Alteração revertida para proteger os dados.','warning','Venda');setSales(next);addAudit('Vendedora alterada pós-venda','Vendas',`#${sellerChange.id} · ${before} → ${after}`);setSellerChange(null);setNewSeller('');setSellerPin('');toast('Vendedora atualizada com auditoria.','success','Venda')};
 const confirmCancellation=()=>{const sale=confirmCancel;if(!sale||sale.status!=='Concluída')return setConfirmCancel(null);const now=new Date().toISOString();let nextSales=sales.map(x=>x.id===sale.id?{...x,status:'Cancelada',cancelledAt:now,reservationActive:false}:x),nextProducts=products,nextFinance=finance,nextClients=clients,nextMovements=safeRead(STORAGE_KEYS.movements,[]),nextInvoices=safeRead(STORAGE_KEYS.invoices,[]);
  nextProducts=products.map(p=>{const line=(sale.items||[]).find(i=>String(i.productId)===String(p.id));return line?{...p,stock:(Number(p.stock)||0)+(Number(line.qty)||0)}:p});
  nextMovements=[...(sale.items||[]).map(i=>({id:uid('mov'),type:'in',product:i.name,productId:i.productId,qty:i.qty,at:now,origin:`Estorno venda #${sale.id}`})),...nextMovements];
  nextFinance=finance.map(x=>x.origin===`sale:${sale.id}`||x.origin===`cash-sale:${sale.id}`?{...x,status:'cancelled',cancelledAt:now}:x);
  nextInvoices=nextInvoices.map(x=>String(x.saleId)===String(sale.id)?{...x,status:'Cancelado',cancelledAt:now}:x);
  nextClients=clients.map(c=>c.name===sale.client?{...c,total:Math.max(0,(Number(c.total)||0)-(Number(sale.total)||0))}:c);
  const curCash=safeRead(STORAGE_KEYS.cashLog,[]),nextCashLog=curCash.map(x=>String(x.saleId)===String(sale.id)?{...x,cancelled:true,cancelledAt:now}:x);
  const writes={[STORAGE_KEYS.sales]:nextSales,[STORAGE_KEYS.products]:nextProducts,[STORAGE_KEYS.finance]:nextFinance,[STORAGE_KEYS.clients]:nextClients,[STORAGE_KEYS.movements]:nextMovements,[STORAGE_KEYS.invoices]:nextInvoices,[STORAGE_KEYS.cashLog]:nextCashLog};
  const tx=commitLocalTransaction(`cancel-sale-${sale.id}`,writes);if(!tx.ok)return toast('O cancelamento foi revertido para evitar inconsistência.','warning','Transação revertida');
  setSales(nextSales);setProducts(nextProducts);setFinance(nextFinance);setClients?.(nextClients);setMovements?.(nextMovements);setInvoices?.(nextInvoices);addAudit('Venda cancelada','Vendas',`#${sale.id} · originada no Caixa`);toast('Venda cancelada e integrações estornadas.','success','Vendas');setConfirmCancel(null)
 };
 return <section className="page"><PageHeader title="Histórico de vendas" subtitle="Consulta das vendas realizadas pelo Caixa. Novas vendas são registradas exclusivamente no módulo Caixa."/>
  <div className="sales-source-notice"><div><Store size={18}/><span><b>Venda somente pelo Caixa</b><small>Esta área é apenas para consulta, rastreabilidade e cancelamento autorizado. Nenhuma venda é criada aqui.</small></span></div><button className="secondary" onClick={()=>setPage?.('cashier')}><Store size={15}/>Ir para o Caixa</button></div>
  <div className="sales-stats"><div><ShoppingCart/><span><b>{cashierSales.length}</b><small>vendas registradas</small></span></div><div><WalletCards/><span><b>{money(billed)}</b><small>faturado ativo</small></span></div><div><RotateCcw/><span><b>{cancelled.length}</b><small>canceladas</small></span></div></div>
  <div className="sales-history-toolbar"><div className="sales-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar venda, cliente, produto, pagamento..."/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="todos">Todos os status</option><option value="concluída">Concluídas</option><option value="cancelada">Canceladas</option></select></div>
  <div className="panel table-panel"><table><thead><tr><th>Venda</th><th>Cliente</th><th>Itens</th><th>Pagamento</th><th>Operador</th><th>Data</th><th>Status</th><th>Total</th><th>Integrações</th><th></th></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><b>#{s.id}</b><small className="table-sub">{s.sessionCode||'Caixa'}</small></td><td>{s.client||'Consumidor'}</td><td>{(s.items||[]).reduce((a,i)=>a+(Number(i.qty)||0),0)}</td><td>{s.payment||'—'}</td><td><b>{s.seller||'—'}</b><small className="table-sub">Operador: {s.operator||'—'}</small></td><td>{s.date||'—'}</td><td><span className={`status ${s.status==='Concluída'?'success':'neutral'}`}>{s.status}</span></td><td>{money(s.total)}</td><td>{s.status==='Concluída'?<span className="flow-tags"><em><Boxes size={13}/>Estoque</em><em><ReceiptText size={13}/>Fiscal</em><em>Financeiro</em></span>:<span className="status neutral">Estornado</span>}</td><td><div className="inline-actions"><button className="secondary tiny" onClick={()=>setDetailSale(s)}><Eye size={13}/>360°</button>{s.status==='Concluída'&&<button className="secondary tiny" onClick={()=>{setSellerChange(s);setNewSeller(s.seller||'')}}><KeyRound size={13}/>Vendedora</button>}{s.status==='Concluída'&&<button className="secondary tiny" onClick={()=>cancelSale(s)}><RotateCcw size={13}/>Cancelar</button>}</div></td></tr>)}{!visible.length&&<tr><td colSpan="10"><p className="empty">Nenhuma venda do Caixa encontrada.</p></td></tr>}</tbody></table></div>
  {detailSale&&<Modal title={`Venda #${detailSale.id} · visão 360°`} subtitle="Registro originado no Caixa, com pagamento, estoque, financeiro e fiscal vinculados." onClose={()=>setDetailSale(null)} wide><div className="field-grid"><div className="field-card"><span>Cliente</span><b>{detailSale.client||'Consumidor'}</b></div><div className="field-card"><span>Total</span><b>{money(detailSale.total)}</b></div><div className="field-card"><span>Status</span><b>{detailSale.status}</b></div><div className="field-card"><span>Pagamento</span><b>{detailSale.payment||'—'}</b></div><div className="field-card"><span>Vendedora</span><b>{detailSale.seller||'—'}</b></div><div className="field-card"><span>Operador</span><b>{detailSale.operator||'—'}</b></div><div className="field-card"><span>Comissão</span><b>{money(detailSale.commission||0)}</b></div><div className="field-card"><span>Taxas pagamento</span><b>{money(detailSale.paymentFees||0)}</b></div><div className="field-card"><span>Margem real</span><b>{money(detailSale.realMargin??0)}</b></div><div className="field-card"><span>Sessão</span><b>{detailSale.sessionCode||'—'}</b></div></div><div className="sale-360-flow"><span>Caixa</span><i>→</i><span>Venda</span><i>→</i><span>Estoque</span><i>→</i><span>Financeiro</span><i>→</i><span>Fiscal</span><i>→</i><span>{detailSale.deliveryRequired?'Entrega':'Sem entrega'}</span><i>→</i><span>{detailSale.returns?.length?'Devolução':'Pós-venda'}</span></div><div className="compact-list">{(detailSale.items||[]).map((i,idx)=><div key={`${i.productId}-${idx}`}><span><b>{i.name}</b><small>{i.sku||'Sem SKU'} · {i.qty} un.</small></span><strong>{money((Number(i.price)||0)*(Number(i.qty)||0))}</strong></div>)}</div></Modal>}
  {sellerChange&&<Modal title="Trocar vendedora da venda" subtitle={`Venda #${sellerChange.id} · alteração auditada`} onClose={()=>{setSellerChange(null);setSellerPin('')}}><div className="form-grid"><label className="form-field wide"><span>Vendedora</span><select value={newSeller} onChange={e=>setNewSeller(e.target.value)}>{activeSalespeople().map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label className="form-field wide"><span>PIN gerencial</span><input type="password" inputMode="numeric" value={sellerPin} onChange={e=>setSellerPin(e.target.value.replace(/\D/g,''))}/></label></div><div className="modal-actions"><button className="primary" onClick={changeSeller}>Confirmar alteração</button></div></Modal>}
  {pinSale&&<Modal title="Autorização gerencial" subtitle={`Cancelar venda #${pinSale.id}`} onClose={()=>{setPinSale(null);setPinValue('')}}><label className="form-field"><span>PIN gerencial</span><input autoFocus type="password" inputMode="numeric" value={pinValue} onChange={e=>setPinValue(e.target.value.replace(/\D/g,''))} onKeyDown={e=>{if(e.key==='Enter')authorizeCancellation()}}/></label><div className="notice"><KeyRound size={15}/>Cancelamentos de venda exigem autorização gerencial.</div><div className="modal-actions"><button className="primary" onClick={authorizeCancellation}>Autorizar</button></div></Modal>}
  <ConfirmDialog open={!!confirmCancel} title="Cancelar venda" message="Estoque, financeiro, fiscal e registro de caixa serão estornados em conjunto." details={confirmCancel?[`#${confirmCancel.id}`,money(confirmCancel.total)]:[]} confirmLabel="Confirmar cancelamento" danger onConfirm={confirmCancellation} onCancel={()=>setConfirmCancel(null)}/>
 </section>
}
