import React,{useMemo,useState}from'react';
import{MessageSquareText,PackageSearch,WalletCards,ReceiptText,X,ArrowUpRight,Search,BarChart3}from'lucide-react';
import{money,isoToday}from'../utils/erpEngine';import{canViewPage}from'../utils/permissions';
export default function FloatingIntelligence({data,setPage,role}){
 const[open,setOpen]=useState(false);const canFinance=canViewPage('finance',role),canStock=canViewPage('stock',role),canReports=canViewPage('reports',role);
 const metrics=useMemo(()=>{const products=data?.products||[],finance=data?.finance||[],invoices=data?.invoices||[];const low=products.filter(p=>(Number(p.stock)||0)<=(Number(p.minStock)||0)).length;const overdue=finance.filter(x=>!['paid','cancelled'].includes(x.status)&&x.due&&x.due<isoToday());return{low,overdue:overdue.length,overdueValue:overdue.reduce((s,x)=>s+Math.max(0,(Number(x.amount)||0)-(Number(x.paidAmount)||0)),0),fiscal:invoices.filter(x=>x.status==='Rascunho').length}},[data]);
 const go=p=>{if(!canViewPage(p,role))return;setPage(p);setOpen(false)};
 return <div className={`floating-intelligence ${open?'open':''}`}>{open&&<div className="floating-assistant-card"><div className="floating-assistant-head"><div><b>Assistente Home</b><span>Atalhos permitidos para {role}</span></div><button onClick={()=>setOpen(false)} aria-label="Fechar"><X size={15}/></button></div><div className="assistant-quick-list">{canStock&&<button onClick={()=>go('stock')}><PackageSearch size={16}/><span>Estoque crítico</span><strong>{metrics.low}</strong></button>}{canFinance&&<button onClick={()=>go('finance')}><WalletCards size={16}/><span>Títulos vencidos</span><strong>{money(metrics.overdueValue)}</strong></button>}{canFinance&&<button onClick={()=>go('finance')}><ReceiptText size={16}/><span>Fiscal pendente</span><strong>{metrics.fiscal}</strong></button>}</div><div className="assistant-actions">{canViewPage('intelligence',role)&&<button onClick={()=>go('intelligence')}><Search size={15}/>Consultar sistema<ArrowUpRight size={14}/></button>}{canReports&&<button onClick={()=>go('reports')}><BarChart3 size={15}/>Análises<ArrowUpRight size={14}/></button>}</div></div>}<button className="floating-assistant-trigger" onClick={()=>setOpen(v=>!v)} aria-label="Abrir assistente"><MessageSquareText size={20}/></button></div>
}
