export const BRAZIL_TZ='America/Sao_Paulo';
export const money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const pct=v=>`${(Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
export function dateInBrazil(value=new Date()){const d=value instanceof Date?value:new Date(value);const parts=new Intl.DateTimeFormat('en-CA',{timeZone:BRAZIL_TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));return`${map.year}-${map.month}-${map.day}`}
export const isoToday=()=>dateInBrazil(new Date());
export const monthKey=d=>(d||isoToday()).slice(0,7);
export const normalize=s=>(s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterByPeriod(items,dateField,period='all'){const list=Array.isArray(items)?items:[];if(period==='all')return list;return list.filter(x=>(x?.[dateField]||'').slice(0,7)===period)}
export function getProductMargin(p){const price=Number(p?.price)||0,cost=Number(p?.cost)||0;return price?((price-cost)/price)*100:0}
export function buildDRE({sales=[],finance=[],period='all'}){
  const ps=filterByPeriod(sales,'date',period).filter(s=>!['Cancelada','Cancelado'].includes(s.status));
  const pf=filterByPeriod(finance,'due',period).filter(x=>x.status!=='cancelled');
  const gross=ps.reduce((s,x)=>s+(Number(x.total)||0),0);
  const cmv=ps.reduce((sum,sale)=>sum+(sale.items||[]).reduce((a,i)=>a+(Number(i.cost)||0)*(Number(i.qty)||1),0),0);
  const returns=ps.reduce((s,x)=>s+(Number(x.returnAmount)||0),0);
  const taxFromSales=ps.reduce((s,x)=>s+(Number(x.taxAmount)||0),0);
  const taxFromFinance=pf.filter(x=>x.type==='pay'&&(x.accountGroup==='Impostos'||/imposto|icms|iss|das|simples/i.test(x.category||''))).reduce((s,x)=>s+(Number(x.amount)||0),0);
  const taxes=taxFromSales+taxFromFinance;
  const operating=pf.filter(x=>x.type==='pay'&&x.accountGroup!=='Custos'&&x.accountGroup!=='Impostos'&&!/mercadoria|fornecedor/i.test(x.category||'')).reduce((s,x)=>s+(Number(x.amount)||0),0);
  const revenueNet=gross-returns-taxes,grossProfit=revenueNet-cmv,operatingResult=grossProfit-operating;
  return{gross,returns,taxes,revenueNet,cmv,grossProfit,operating,operatingResult,net:operatingResult};
}
export function buildCashForecast(finance=[],bankBalance=0,days=90){
  const today=isoToday(),endDate=new Date(`${today}T12:00:00`);endDate.setDate(endDate.getDate()+days);const end=dateInBrazil(endDate);
  const open=(Array.isArray(finance)?finance:[]).filter(x=>!['paid','cancelled'].includes(x.status)&&x.due&&x.due>=today&&x.due<=end).sort((a,b)=>String(a.due).localeCompare(String(b.due)));
  let balance=Number(bankBalance)||0;const points=[{date:today,balance,in:0,out:0}],byDate={};
  for(const x of open){const k=x.due;byDate[k]??={in:0,out:0};byDate[k][x.type==='receive'?'in':'out']+=Math.max(0,(Number(x.amount)||0)-(Number(x.paidAmount)||0))}
  for(const [date,v] of Object.entries(byDate).sort(([a],[b])=>a.localeCompare(b))){balance+=v.in-v.out;points.push({date,balance,...v})}return points;
}
export function deriveAlerts({products=[],finance=[],sales=[],purchases=[],invoices=[]}){const today=isoToday();const low=products.filter(p=>p.active!==false&&(Number(p.stock)||0)<=(Number(p.minStock)||0));const overdue=finance.filter(x=>!['paid','cancelled'].includes(x.status)&&x.due<today);const ncm=products.filter(p=>p.active!==false&&!p.ncmVerified);const draftNF=invoices.filter(x=>x.status==='Rascunho');const latePurchases=purchases.filter(x=>x.status!=='Recebido'&&x.eta&&x.eta<today);const soon=Date.now()+86400000;const expiring=sales.filter(s=>s.status==='Orçamento'&&s.reservationActive&&s.reservationExpiresAt&&new Date(s.reservationExpiresAt).getTime()<=soon&&new Date(s.reservationExpiresAt).getTime()>Date.now());return[low.length&&{id:'auto-low',title:'Estoque abaixo do mínimo',text:`${low.length} produto(s) precisam de reposição.`,page:'stock',kind:'warn',priority:1},overdue.length&&{id:'auto-overdue',title:'Títulos vencidos',text:`${overdue.length} lançamento(s) financeiros estão vencidos.`,page:'finance',kind:'warn',priority:1},expiring.length&&{id:'auto-reservation',title:'Reservas perto de vencer',text:`${expiring.length} orçamento(s) expiram nas próximas 24 horas.`,page:'sales',kind:'warn',priority:1},ncm.length&&{id:'auto-ncm',title:'NCM pendente',text:`${ncm.length} produto(s) ainda precisam de validação fiscal.`,page:'products',kind:'info',priority:2},draftNF.length&&{id:'auto-nf',title:'Rascunhos fiscais',text:`${draftNF.length} documento(s) aguardam tratamento.`,page:'finance',kind:'info',priority:2},latePurchases.length&&{id:'auto-purchase',title:'Compras atrasadas',text:`${latePurchases.length} pedido(s) passaram da previsão.`,page:'purchases',kind:'warn',priority:2}].filter(Boolean)}
export function suggestReorder(product,sales=[]){const sold=(sales||[]).reduce((s,sale)=>s+(sale.items||[]).filter(i=>String(i.productId)===String(product.id)).reduce((a,i)=>a+(Number(i.qty)||0),0),0);const min=Math.max(Number(product.minStock)||0,Math.ceil(sold/3));const available=(Number(product.stock)||0)-(Number(product.reserved)||0);return Math.max(0,min*2-available)}
export function buildExecutiveInsights({products=[],finance=[],sales=[],purchases=[],invoices=[]}){const dre=buildDRE({sales,finance});const low=products.filter(p=>p.active!==false&&p.stock<=p.minStock);const overdue=finance.filter(x=>!['paid','cancelled'].includes(x.status)&&x.due<isoToday());const openReceive=finance.filter(x=>x.type==='receive'&&!['paid','cancelled'].includes(x.status)).reduce((s,x)=>s+(Number(x.amount)||0),0);const openPay=finance.filter(x=>x.type==='pay'&&!['paid','cancelled'].includes(x.status)).reduce((s,x)=>s+(Number(x.amount)||0),0);return[{tone:dre.net>=0?'good':'danger',title:'Resultado gerencial',value:money(dre.net),detail:`Margem líquida ${dre.gross?pct(dre.net/dre.gross*100):'0%'}`,page:'finance'},{tone:overdue.length?'danger':'good',title:'Vencidos',value:String(overdue.length),detail:overdue.length?'Existem títulos que exigem ação':'Nenhum título vencido',page:'finance'},{tone:low.length?'warn':'good',title:'Reposição',value:String(low.length),detail:low.length?'Produtos abaixo do mínimo':'Estoque sem rupturas críticas',page:'stock'},{tone:openReceive-openPay>=0?'good':'warn',title:'Exposição de caixa',value:money(openReceive-openPay),detail:'A receber menos a pagar em aberto',page:'finance'}]}
export function interpretCommand(text,{products=[],finance=[],sales=[],purchases=[],invoices=[]}){const t=normalize(text),number=(t.match(/(\d+[\.,]?\d*)\s*%/)||[])[1];if(/estoque (baixo|critico|mínimo|minimo)|repor|reposicao|reposição/.test(t)){const rows=products.filter(p=>p.active!==false&&p.stock<=p.minStock).map(p=>({Produto:p.name,SKU:p.sku,Estoque:p.stock,Mínimo:p.minStock,Sugerido:suggestReorder(p,sales)}));return{kind:'table',title:'Reposição sugerida',summary:`${rows.length} produto(s) abaixo do mínimo.`,rows,action:{type:'navigate',page:'stock',label:'Abrir estoque'}}}if(/margem/.test(t)){const limit=number?Number(number.replace(',','.')):35;const rows=products.filter(p=>p.active!==false&&getProductMargin(p)<limit).map(p=>({Produto:p.name,SKU:p.sku,Margem:pct(getProductMargin(p)),Custo:money(p.cost),Preço:money(p.price)}));return{kind:'table',title:`Produtos com margem abaixo de ${limit}%`,summary:`${rows.length} produto(s) encontrados.`,rows,action:{type:'navigate',page:'products',label:'Abrir produtos'}}}if(/conta|titulo|venc/.test(t)){const overdue=finance.filter(x=>!['paid','cancelled'].includes(x.status)&&x.due<isoToday());return{kind:'table',title:'Títulos vencidos',summary:`${overdue.length} lançamento(s) vencido(s).`,rows:overdue.map(x=>({Descrição:x.desc,Tipo:x.type==='receive'?'Receber':'Pagar',Vencimento:x.due,Valor:money(x.amount)})),action:{type:'navigate',page:'finance',label:'Abrir financeiro'}}}if(/dre|resultado|lucro/.test(t)){const d=buildDRE({sales,finance});return{kind:'cards',title:'Resultado gerencial',summary:'DRE calculada com as informações atuais do ERP.',cards:[['Receita',money(d.gross)],['CMV',money(d.cmv)],['Despesas',money(d.operating)],['Resultado',money(d.net)]],action:{type:'navigate',page:'finance',label:'Abrir DRE completa'}}}return{kind:'text',title:'Comando entendido parcialmente',summary:'Tente perguntas como “produtos com margem abaixo de 35%”, “títulos vencidos”, “DRE” ou “estoque baixo”.'}}
