import{safeReadArray}from'./storage';
import{isoToday}from'./erpEngine';
const arr=(k)=>safeReadArray(k,[]);
export function runIntegrityCheck(){
 const products=arr('home-products-v12'),sales=arr('home-sales-v12'),finance=arr('home-finance-v12'),invoices=arr('home-nf-docs-v16'),purchases=arr('home-purchases-v12'),movements=arr('home-stock-log-v16'),bills=arr('homeerp-bills-v211');
 const warranties=arr('home-warranties-v29'),deliveries=arr('home-deliveries-v29'),orders=arr('home-orders-v217');
 const issues=[];
 const all=[['Produtos',products],['Vendas',sales],['Financeiro',finance],['Fiscal',invoices],['Compras',purchases],['Estoque',movements],['Boletos',bills],['Garantias',warranties],['Entregas',deliveries],['Pedidos',orders]];
 for(const[module,list]of all){const seen=new Set();for(const x of list){if(!x||typeof x!=='object'){issues.push({level:'danger',module,text:'Registro inválido encontrado.'});continue}const id=String(x.id??'');if(!id){issues.push({level:'warn',module,text:'Registro sem ID.'});continue}if(seen.has(id))issues.push({level:'danger',module,text:`ID duplicado ${id}.`});seen.add(id)}}
 const skuMap=new Map(),quoteReservations=new Map();
 for(const s of sales.filter(x=>x?.status==='Orçamento'&&x?.reservationActive!==false)){for(const i of Array.isArray(s.items)?s.items:[])quoteReservations.set(String(i.productId),(quoteReservations.get(String(i.productId))||0)+(Number(i.qty)||0));if(s.reservationExpiresAt&&String(s.reservationExpiresAt).slice(0,10)<isoToday())issues.push({level:'warn',module:'Vendas',text:`Orçamento #${s.id} está com reserva vencida e deve liberar o estoque.`})}
 for(const p of products){const sku=String(p.sku||'').trim().toUpperCase();if(!sku)issues.push({level:'warn',module:'Produtos',text:`${p.name||'Produto'} sem SKU.`});else if(skuMap.has(sku))issues.push({level:'danger',module:'Produtos',text:`SKU duplicado ${sku}: ${skuMap.get(sku)} / ${p.name}`});else skuMap.set(sku,p.name);if((Number(p.stock)||0)<0)issues.push({level:'danger',module:'Estoque',text:`${p.name} com estoque negativo (${p.stock}).`});const expected=quoteReservations.get(String(p.id))||0;if((Number(p.reserved)||0)!==expected)issues.push({level:'warn',module:'Estoque',text:`${p.name}: reservado ${p.reserved||0}, mas orçamentos ativos somam ${expected}.`});if(!p.ncmVerified)issues.push({level:'warn',module:'Fiscal',text:`${p.name} com NCM não confirmado.`})}
 const productIds=new Set(products.map(p=>String(p.id))),saleIds=new Set(sales.map(s=>String(s.id))),purchaseIds=new Set(purchases.map(p=>String(p.id))),billIds=new Set(bills.map(b=>String(b.id)));
 for(const s of sales){for(const i of Array.isArray(s.items)?s.items:[])if(i.productId&&!productIds.has(String(i.productId)))issues.push({level:'warn',module:'Vendas',text:`Venda #${s.id} referencia produto inexistente (${i.name||i.productId}).`});if(s.status==='Cancelada'&&finance.some(x=>(x.origin===`sale:${s.id}`||x.origin===`cash-sale:${s.id}`)&&x.status!=='cancelled'))issues.push({level:'danger',module:'Financeiro',text:`Venda #${s.id} cancelada ainda possui lançamento financeiro ativo.`})}
 for(const f of finance){const o=String(f.origin||'');if((o.startsWith('sale:')||o.startsWith('cash-sale:'))&&!saleIds.has(o.replace(/^cash-sale:|^sale:/,'')))issues.push({level:'warn',module:'Financeiro',text:`Lançamento ${f.desc||f.id} referencia venda inexistente (${o}).`});if(o.startsWith('purchase:')&&!purchaseIds.has(o.replace('purchase:','')))issues.push({level:'warn',module:'Financeiro',text:`Lançamento ${f.desc||f.id} referencia compra inexistente (${o}).`});if(o.startsWith('bill:')&&!billIds.has(o.replace('bill:',''))&&f.status!=='cancelled')issues.push({level:'warn',module:'Financeiro',text:`Lançamento ${f.desc||f.id} referencia boleto inexistente (${o}).`})}
 for(const n of invoices)if(n.saleId&&!saleIds.has(String(n.saleId)))issues.push({level:'warn',module:'Fiscal',text:`Documento fiscal ${n.id} referencia venda inexistente #${n.saleId}.`});
 for(const p of purchases)if(p.status==='Recebido'&&!finance.some(x=>x.origin===`purchase:${p.id}`))issues.push({level:'danger',module:'Compras',text:`Compra #${p.id} recebida sem conta a pagar vinculada.`});
 for(const b of bills){const linked=finance.filter(x=>x.origin===`bill:${b.id}`&&x.status!=='cancelled');if(!linked.length)issues.push({level:'warn',module:'Boletos',text:`Boleto ${b.supplier||b.id} sem conta a pagar vinculada.`});if(b.line){const duplicates=bills.filter(x=>x.id!==b.id&&String(x.line||'').replace(/\D/g,'')===String(b.line).replace(/\D/g,''));if(duplicates.length)issues.push({level:'danger',module:'Boletos',text:`Linha digitável duplicada em ${b.supplier||b.id}.`})}}
 for(const w of warranties)if(w.saleId&&!saleIds.has(String(w.saleId)))issues.push({level:'warn',module:'Garantias',text:`Garantia ${w.id} referencia venda inexistente.`});
 for(const d of deliveries)if(d.saleId&&!saleIds.has(String(d.saleId)))issues.push({level:'warn',module:'Entregas',text:`Entrega ${d.id} referencia venda inexistente.`});
 for(const o of orders)if(o.saleId&&!saleIds.has(String(o.saleId)))issues.push({level:'warn',module:'Pedidos',text:`Pedido ${o.id} referencia venda inexistente.`});
 for(const s of sales.filter(x=>x?.status==='Concluída'))if(!orders.some(o=>String(o.saleId)===String(s.id)))issues.push({level:'warn',module:'Pedidos',text:`Venda #${s.id} concluída ainda não possui pedido operacional.`});
 return{at:new Date().toISOString(),counts:{products:products.length,sales:sales.length,finance:finance.length,invoices:invoices.length,purchases:purchases.length,movements:movements.length,bills:bills.length,warranties:warranties.length,deliveries:deliveries.length,orders:orders.length},issues,ok:issues.every(x=>x.level!=='danger')};
}
