import fs from'fs';import path from'path';import{spawnSync}from'child_process';
const root=process.cwd(),checks=[];const pass=(name,ok)=>checks.push({name,ok});
const cash=fs.readFileSync(path.join(root,'src/pages/Cashier.jsx'),'utf8');
const stock=fs.readFileSync(path.join(root,'src/pages/Stock.jsx'),'utf8');
const finance=fs.readFileSync(path.join(root,'src/pages/Finance.jsx'),'utf8');
const sales=fs.readFileSync(path.join(root,'src/pages/Sales.jsx'),'utf8');
const reports=fs.readFileSync(path.join(root,'src/pages/Reports.jsx'),'utf8');
const orders=fs.readFileSync(path.join(root,'src/pages/Orders.jsx'),'utf8');
pass('Caixa exige vendedora',cash.includes("if(!seller)return toast('Selecione a vendedora"));
pass('PIN rápido por vendedora',cash.includes('verifySellerPin'));
pass('Fechamento cego',cash.includes('blindCloseRevealed'));
pass('Limite de desconto',cash.includes('sellerDiscountLimit'));
pass('Sangria alta com PIN',cash.includes('home-high-withdrawal-limit'));
pass('Crediário parcelado',cash.includes("creditPlan=p.type==='Crediário'")&&cash.includes("(cardCredit||creditPlan)?Math.max(1"));
pass('Entrega automática',cash.includes('deliveryRequired')&&cash.includes("home-deliveries-v29"));
pass('Margem real',cash.includes('realMargin'));
pass('Estoque com inventário cego',stock.includes('blindInventory'));
pass('Transferência entre locais',stock.includes('stock-transfer'));
pass('Sugestão de compra',stock.includes("tab==='reorder'"));
pass('Curva ABC',reports.includes('Curva ABC'));
pass('Estoque parado',reports.includes('Estoque parado'));
pass('Cobrança financeira',finance.includes("tab==='collection'"));
pass('DRE por centro de custo',finance.includes('DRE por centro de custo'));
pass('Fluxo por cenário',finance.includes('scenarioFactor'));
pass('Troca de vendedora auditada',sales.includes('Vendedora alterada pós-venda'));
pass('Pedido automático após venda',cash.includes('home-orders-v217')&&cash.includes("status:'Aguardando separação'"));
pass('Fluxo operacional de pedidos',orders.includes("'Aguardando separação':'Em separação'")&&orders.includes("'Em rota':'Concluído'"));
pass('Financeiro com sourceType/sourceId',cash.includes("sourceType:'sale'")&&finance.includes("sourceType:'bill'"));
const audit=spawnSync(process.execPath,['scripts/static-audit.mjs'],{cwd:root,encoding:'utf8'});pass('Auditoria estática',audit.status===0);
for(const c of checks)console.log(`${c.ok?'OK':'FALHA'} - ${c.name}`);const failed=checks.filter(x=>!x.ok);console.log(`\n${checks.length-failed.length}/${checks.length} verificações aprovadas.`);if(failed.length)process.exit(1);
